name: Docker Build and Push

on:
  push:
    branches:
      - main
      - development
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build_and_push_alpha_image:
    name: Push Alpha Docker image (PR)
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Check out repository code ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Get package version
        id: package_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx ğŸš€
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub ğŸš¢
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Build and push alpha image ğŸ—ï¸
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            VUE_APP_API_URL=
            BASE_URL=
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME}}/recommendarr:alpha
            ${{ secrets.DOCKER_HUB_USERNAME}}/recommendarr:alpha-v${{ steps.package_version.outputs.VERSION }}
            ${{ secrets.DOCKER_HUB_USERNAME}}/recommendarr:pr-${{ github.event.pull_request.number }}

  build_and_push_dev_image:
    name: Push Development Docker image
    if: github.event_name == 'push' && github.ref == 'refs/heads/development'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Check out repository code ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Get package version
        id: package_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx ğŸš€
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub ğŸš¢
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Build and push dev image ğŸ—ï¸
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          build-args: |
            VUE_APP_API_URL=
            BASE_URL=
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME}}/recommendarr:dev
            ${{ secrets.DOCKER_HUB_USERNAME}}/recommendarr:dev-v${{ steps.package_version.outputs.VERSION }}
            ${{ secrets.DOCKER_HUB_USERNAME}}/recommendarr:dev-${{ github.sha }}

  build_and_push_image:
    name: Push Production Docker image
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write

    steps:
      - name: Check out repository code ğŸ›ï¸
        uses: actions/checkout@v4

      - name: Get package version
        id: package_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx ğŸš€
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub ğŸš¢
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN}}

      - name: Build and push unified image ğŸ—ï¸
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64,linux/amd64
          push: true
          build-args: |
            VUE_APP_API_URL=
            BASE_URL=
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME}}/recommendarr:${{ github.sha }}
            ${{ secrets.DOCKER_HUB_USERNAME}}/recommendarr:v${{ steps.package_version.outputs.VERSION }}
            ${{ secrets.DOCKER_HUB_USERNAME}}/recommendarr:latest